### ISSUE TITLE
attiny code for shining pig?

### ISSUE THREAD

**Issue by reaganryl** [effectspcbs/horizon-projects#1]
Hi- is there some code to go with the shining pig? what does it do? thanks  :)

**Comment by yann-ygn** [comment]
Hello, there is : it is the simple piece of code that drives the relay-based switching system, it is common to all the effects. You can find it [here](https://github.com/effectspcbs/platformio-avr/tree/master/relay_switching_v2).

**Comment by reaganryl** [comment]
thanks!
